version: '3.7'
services:
  mongodb_test:
    container_name: local-mongo
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    ports:
      - 27017:27017
    # volumes:
    #   - mongodb_data_container:/data/db
    networks:
      - parking-local

  # postgres_test:
  #   container_name: local-pg
  #   image: bitnami/postgresql
  #   ports:
  #     - 5432:5432
  #   environment:
  #     POSTGRES_USER: root
  #     POSTGRES_PASSWORD: rootpassword
  #     POSTGRES_DB: parking
  #   networks:
  #     - parking-local
  
  mysql_test:
    container_name: local-mysql
    image: mysql:latest
    # command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3306:3306
    # volumes:
    #   - mysqltest:/var/lib/mysql
    environment:
      MYSQL_DATABASE: parking
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: rootpassword
    networks:
      - parking-local
    
networks:
  parking-local:


# volumes:
#   mongodb_data_container:
